### PR TITLE
The weirdly bordered icon.

### PR DESCRIPTION
**Pull request by ghostslayer989**

### CODE REVIEW

**Comment by saricden** [comment]
:tada: :shipit: :shipit: :shipit:

**Comment by ghostslayer989** [comment]
HALT

**Comment by ghostslayer989** [comment]
YOU VIOLATED THE LAW

**Comment by ghostslayer989** [comment]
The ships.

**Comment by ghostslayer989** [comment]
You abused the ships.

**Comment by saricden** [comment]
@ghostslayer989 check the stream chat ;D

**Pull request merged**
